### ISSUE TITLE
Faias to start with error: ERROR basic.BasicReservationService  - No Zone for ap-southeast-2c

### ISSUE THREAD

**Issue by hermes-pimentel** [Teevity/ice#198]
Complete error message:

| Error 2016-02-22 21:20:59,295 [localhost-startStop-1] ERROR basic.BasicReservationService  - No Zone for ap-southeast-2c
| Error 2016-02-22 21:20:59,299 [localhost-startStop-1] ERROR basic.BasicReservationService  - failed to poll reservation prices
Message: null
    Line | Method
->>  177 | pollAPI                          in com.netflix.ice.basic.BasicReservationService

---

|    106 | init                             in     ''
|     95 | <init> . . . . . . . . . . . . . in com.netflix.ice.processor.ProcessorConfig
|    186 | doCall                           in BootStrap$_closure1
|    327 | evaluateEnvironmentSpecificBlock in grails.util.Environment
|    320 | executeForEnvironment            in     ''
|    296 | executeForCurrentEnvironment . . in     ''
|    266 | run                              in java.util.concurrent.FutureTask
|   1142 | runWorker . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor
|    617 | run                              in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . . . . . . . . . . .  in java.lang.Thread
| Error java.lang.RuntimeException: failed to polo reservation prices for null

Anyone have a workaround for this ?

**Comment by NitriKx** [comment]
As a temporary workaround, I think you can add the following attribute in com.netflix.ice.tag.Zone

```
public static final Zone AP_SOUTHEAST_1C = new Zone(Region.AP_SOUTHEAST_1, "ap-southeast-1c");
```

**Comment by minac** [comment]
Thanks, that fixed it as a workaround. For clarification the file you mean to edit is src/java/com/netflix/ice/tag/Zone.java
