### ISSUE TITLE
how do i run ice reader

### ISSUE THREAD

**Issue by mpodber1971** [Teevity/ice#213]
documentation explains how to run ice processor as follows:
./grailsw -Dice.s3AccessKeyId=<s3AccessKeyId> -Dice.s3SecretKey=<s3SecretKey> run-app

what are steps to run ice reader?

**Comment by interactivetech** [comment]
In the ice.properties file, did you set ice.reader to true? This will enable the app to launch the reader when you run the ./grailsw command.

**Comment by mpodber1971** [comment]
yes, it is set to true so this probably isn't related to the issue i am having

**Comment by ghaber** [comment]
if you have that property set, once you run ice, the reader is running, what is the error or problem you are having?

**Comment by mpodber1971** [comment]
@ghaber , the error I am havingis when i pull up the URL, it shows the selection criteria but doesn't show any actual data. just a spinning wheel
