### ISSUE TITLE
install.sh fails with dependencies error.

### ISSUE THREAD

**Issue by gjws** [Teevity/ice#219]
Hi all,

I'm trying to install ice on an ec2 instance running amazon linux. After a default instance build I ran a "yum update" then in the /opt dir I ran "sudo git clone https://github.com/Netflix/ice.git"

In /opt/ice I ran ./setup,sh (as root) and this is the output I received:

Installing debian packages
sudo: apt-get: command not found
Already up-to-date.
| Downloading: ant-trax-1.7.1.jar
:: problems summary ::
:::: WARNINGS
                module not found: org.grails.plugins#tomcat;8.0.20
        ==== grailsPlugins: tried
          -- artifact org.grails.plugins#tomcat;8.0.20!tomcat.zip:
          /opt/ice/lib/tomcat-8.0.20.zip
        ==== grailsHome: tried
          /root/.grails/wrapper/2.2.1/grails-2.2.1/lib/org.grails.plugins/tomcat/ivy-8.0.20.xml
          -- artifact org.grails.plugins#tomcat;8.0.20!tomcat.zip:
          /root/.grails/wrapper/2.2.1/grails-2.2.1/lib/org.grails.plugins/tomcat/jars/tomcat-8.0.20.zip
          /root/.grails/wrapper/2.2.1/grails-2.2.1/lib/org.grails.plugins/tomcat/bundles/tomcat-8.0.20.zip
        ==== grailsHome: tried
          /root/.grails/wrapper/2.2.1/grails-2.2.1/src/libs/tomcat-8.0.20.xml
          -- artifact org.grails.plugins#tomcat;8.0.20!tomcat.zip:
          /root/.grails/wrapper/2.2.1/grails-2.2.1/src/libs/tomcat-8.0.20.zip
        ==== grailsHome: tried
          /root/.grails/wrapper/2.2.1/grails-2.2.1/dist/tomcat-8.0.20.xml
          -- artifact org.grails.plugins#tomcat;8.0.20!tomcat.zip:
          /root/.grails/wrapper/2.2.1/grails-2.2.1/dist/tomcat-8.0.20.zip
        ==== grailsHome: tried
          /root/.grails/2.2.1/cached-installed-plugins/tomcat-8.0.20.xml
          -- artifact org.grails.plugins#tomcat;8.0.20!tomcat.zip:
          /root/.grails/2.2.1/cached-installed-plugins/tomcat-8.0.20.zip
        ==== grailsHome: tried
          /root/.grails/wrapper/2.2.1/grails-2.2.1/plugins/tomcat-8.0.20.pom
          -- artifact org.grails.plugins#tomcat;8.0.20!tomcat.zip:
          /root/.grails/wrapper/2.2.1/grails-2.2.1/plugins/tomcat-8.0.20.zip
        ==== grailsCentral: tried
          http://grails.org/plugins/grails-tomcat/tags/RELEASE_8.0.20/tomcat-8.0.20.pom
          -- artifact org.grails.plugins#tomcat;8.0.20!tomcat.zip:
          http://grails.org/plugins/grails-tomcat/tags/RELEASE_8.0.20/grails-tomcat-8.0.20.zip
        ==== mavenCentral: tried
          http://repo1.maven.org/maven2/org/grails/plugins/tomcat/8.0.20/tomcat-8.0.20.pom
          -- artifact org.grails.plugins#tomcat;8.0.20!tomcat.zip:
          http://repo1.maven.org/maven2/org/grails/plugins/tomcat/8.0.20/tomcat-8.0.20.zip
                ::::::::::::::::::::::::::::::::::::::::::::::
                ::          UNRESOLVED DEPENDENCIES         ::
                ::::::::::::::::::::::::::::::::::::::::::::::
                :: org.grails.plugins#tomcat;8.0.20: not found
                ::::::::::::::::::::::::::::::::::::::::::::::

| Downloading: spring-test-3.1.4.RELEASE.jar
| Error Failed to resolve dependencies (Set log level to 'warn' in BuildConfig.groovy for more information):
- org.grails.plugins:tomcat:8.0.20

rm: cannot remove ‘grails-app/i18n/messages.properties’: No such file or directory
mkdir: cannot create directory ‘/root/ice_processor’: File exists
mkdir: cannot create directory ‘/root/ice_reader’: File exists
Please enter the name of the bucket Ice will read Amazon billing information from:
-> aaa.bbb.cccc
Please enter the name of the bucket Ice will write processed billing information to:
-> aaa.ccc.dddd
Ice is now ready to run as a processor. If you want to run the reader, edit:
/root/ice/src/java/ice.properties
and alter the appropriate flags. You can now start Ice by running the following from the Ice root directory:
./grailsw -Djava.net.preferIPv4Stack=true -Dice.s3AccessKeyId=<access key ID> -Dice.s3SecretKey=<access key> run-app

Not sure if it's an unsupported OS, I'm doing something wrong, or an update is needed somewhere in ice?

**Comment by puvitsingh** [comment]
make sure your ec2-user owns your /mnt and /opt/ice folders: {{ chown -R }}

**Comment by egonbraun** [comment]
I am having the same problem and I am running this as root inside a container. I am not sure if this is related to permissions but actually to the version of the plugin.
