### ISSUE TITLE
install done but can't  start?

### ISSUE THREAD

**Issue by zhangsj** [Teevity/ice#248]
root@AWS-TEST-SVN:/home/prod/softwares/ice/ice# ./install.sh 
Installing debian packages
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version.
unzip is already the newest version.
wget is already the newest version.
openjdk-6-jdk is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 162 not upgraded.
Already up-to-date.
| Error Error occurred running Grails CLI: null (Use --stacktrace to see the full trace)
rm: cannot remove ‘grails-app/i18n/messages.properties’: No such file or directory
mkdir: cannot create directory ‘/root/ice_processor’: File exists
mkdir: cannot create directory ‘/root/ice_reader’: File exists
Please enter the name of the bucket Ice will read Amazon billing information from:
-> bill
Please enter the name of the bucket Ice will write processed billing information to:
-> bill/ice
sed: -e expression #1, char 163: unknown option to `s'
Ice is now ready to run as a processor. If you want to run the reader, edit:
/root/ice/src/java/ice.properties
and alter the appropriate flags. You can now start Ice by running the following from the Ice root directory:
./grailsw -Djava.net.preferIPv4Stack=true -Dice.s3AccessKeyId=<access key ID> -Dice.s3SecretKey=<access key> run-app
root@AWS-TEST-SVN:/home/prod/softwares/ice/ice# ./grailsw run-app
grailsw: JAVA_HOME environment variable is not set

**Comment by ghaber** [comment]
I think you have an issue with the JAVA_HOME environment variable that is not set. Google it depending on your operating system.

For example:
[https://askubuntu.com/questions/175514/how-to-set-java-home-for-java](url)
