### ISSUE TITLE
ERROR basic.BasicReservationService  - No Zone for ap-southeast-2c

### ISSUE THREAD

**Issue by priyankagupta0506** [Teevity/ice#256]
after giving proper timezone and ice.properties file ,this error is coming while building from docker-compose.Kindly help on it.Where to set this zone while doing from docker-compose.
![image](https://user-images.githubusercontent.com/27766672/28571180-4a5eea76-715f-11e7-8906-5ee1982eb120.png)
![image](https://user-images.githubusercontent.com/27766672/28571196-6084fd68-715f-11e7-8d42-1dd9ff5fb45a.png)

**Comment by nfonrose** [comment]
Hi,

Are you using the lastest version ?

Nicolas

**Comment by priyankagupta0506** [comment]
yes , i was using latest version then switched to 1.0.0 . Now its working!!

**Comment by nfonrose** [comment]
Happy that it works for you :-)

But it should be working with the latest version (which is 1.1.1).
Is that the one you were using ?

If you do, your config file should include the ice.billing_s3region
property.
It does not appear on your configuration file screenshot. Was it in the
file ?

Nicolas

--
Nicolas Fonrose | Teevity | Founder
+33.6.61.35.43.31
https://teevity.com - Cloud Costs Analytics built on NetflixOSS
twitter - @nfonrose / @teevity


On Tue, Jul 25, 2017 at 3:23 PM, priyankagupta0506 <notifications@github.com

**Comment by priyankagupta0506** [comment]
thanks!   ice.billing_s3region .. i wanted this only for inserting in that file !!
