### ISSUE TITLE
Limiting Accounts

### ISSUE THREAD

**Issue by owenmorgan** [Teevity/ice#257]
Hello, is there a way of limiting access to a list of accounts only?

**Comment by nfonrose** [comment]
Hi,

You can filter the billing file content that you feed Ice with (an AWS
Lambda can do the trick).
Apart from that, in the OSS version, there isn't an account exclusion
mecanism.

Nicolas

PS : I think I remember that, years ago, someone made a Pull Request for
something like that.
But I can't remember who and when exactly.


--
Nicolas Fonrose | Teevity | Founder
+33.6.61.35.43.31
https://teevity.com - Cloud Costs Analytics built on NetflixOSS
twitter - @nfonrose / @teevity

**Comment by owenmorgan** [comment]
ah.. so pickup and filter out accounts in lambda and drop into another bucket for Ice.. that should do the trick.
