### ISSUE TITLE
Prerequisite Error : install.sh has GRAILS_VERSION=2.2.1 

### ISSUE THREAD

**Issue by azimkhatri** [Teevity/ice#261]
Prerequisite says to Install Grails 2.4.4 but the install.sh has GRAILS_VERSION=2.2.1 
Please can you update the script install.sh with correct version.

**Comment by NitriKx** [comment]
#182 Should do it

**Comment by NitriKx** [comment]
#200 will also improve it, these two PR should be merged in the next release

**Comment by NitriKx** [comment]
Problem fixed in v1.1.2
