### ISSUE TITLE
difference between ec2 and ec2_instance

### ISSUE THREAD

**Issue by utsav2307** [Teevity/ice#265]
i see two options in my billing in ice console- ec2 and ec2_instance. Can anyone explain how they are different?

**Comment by nfonrose** [comment]
Hi,

The ec2_instance "product" is for the instances themselves. All other costs
related to instances (like network in/out, ...) is categorized under the
ec2 product.

Nicolas

--
Nicolas Fonrose | Teevity | Founder
+33.6.61.35.43.31
https://teevity.com - Cloud Costs Analytics built on NetflixOSS
twitter - @nfonrose / @teevity
