### ISSUE TITLE
ERROR BootStrap  - Startup failed - Null Pointer Exception

### ISSUE THREAD

**Issue by Boojs** [Teevity/ice#271]
Hi there,

I am having this issue constantly while trying to run this app. I had it running previously just fine but now it just wont run. Its running on alpine linux in a docker container. Using this repo https://github.com/jonbrouse/docker-ice

The error that keeps coming up is:
`2017-10-06 21:06:42,308 [localhost-startStop-1] INFO  BootStrap  - Starting ice...
| Error java.lang.NullPointerException
| Error         at java.util.Hashtable.put(Hashtable.java:459)
| Error         at java.util.Properties.setProperty(Properties.java:166)
| Error         at java_util_Properties$setProperty$2.call(Unknown Source)
| Error         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
| Error         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
| Error         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
| Error         at BootStrap$_closure1.doCall(BootStrap.groovy:148)
| Error         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
| Error         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error         at java.lang.reflect.Method.invoke(Method.java:498)
| Error         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
| Error         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
| Error         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
| Error         at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
| Error         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
| Error         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1081)
| Error         at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
| Error         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
| Error         at groovy.lang.Closure.call(Closure.java:423)
| Error         at groovy.lang.Closure.call(Closure.java:417)
| Error         at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
| Error         at grails.util.Environment.executeForEnvironment(Environment.java:320)
| Error         at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
| Error         at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
| Error         at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:78)
| Error         at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationContext(GrailsContextLoaderListener.java:110)
| Error         at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
| Error         at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4728)
| Error         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5162)
| Error         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
| Error         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
| Error         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
| Error         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
| Error         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
| Error         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
| Error         at java.lang.Thread.run(Thread.java:748)
| Error 2017-10-06 21:06:42,400 [localhost-startStop-1] ERROR BootStrap  - Startup failed
Message: null
    Line | Method
->>  459 | put                              in java.util.Hashtable
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|    166 | setProperty                      in java.util.Properties
|    148 | doCall . . . . . . . . . . . . . in BootStrap$_closure1
|    327 | evaluateEnvironmentSpecificBlock in grails.util.Environment
|    320 | executeForEnvironment . . . . .  in     ''
|    296 | executeForCurrentEnvironment     in     ''
|    266 | run . . . . . . . . . . . . . .  in java.util.concurrent.FutureTask
|   1149 | runWorker                        in java.util.concurrent.ThreadPoolExecutor
|    624 | run . . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    748 | run                              in java.lang.Thread
`
Any help appreciated!

**Comment by NitriKx** [comment]
Hi @Boojs, have you define `ice.billing_s3bucketregion` in your ice.properties?

**Comment by Boojs** [comment]
@NitriKx you are 100% correct. Sorry for not updating this thread. I resolved this issue defining that field. Was just an oversight on my part

**Comment by Boojs** [comment]
@NitriKx Also thank you for getting back to me! Appreciate it
