### ISSUE TITLE
Billing records stop

### ISSUE THREAD

**Issue by klausfiend** [Teevity/ice#279]
This one has me scratching my head. I've looked over the detailed billing files from November and December, and all the information is in there and looks normal, but for some reason, our billing records stopped dead at 9 AM on November 19th (see screenshot attached).

Every configuration of the application I've tried -- standalone, on a VM, or in a container -- shows me the same dismal picture, and I can't find anything in the logs to explain what might have happened.

Has this happened to anyone else? Where should I dig around in the code to debug this?

![aws_usage](https://user-images.githubusercontent.com/16393974/33926680-efd26b66-df93-11e7-8e92-0d9641abb500.png)

**Comment by nfonrose** [comment]
The best way to debug this is to create a very small billing file that
contains just two lines:

   - One that works (from before Nov 19th)
   - One after that date

Don't forget the include header line. You can also disable RI polling.
And then try to debug from there. This will reduce the log noise while you
debug.

Nicolas

--
Nicolas Fonrose | Teevity | Founder
+33.6.61.35.43.31
https://teevity.com - Cloud Costs Analytics built on NetflixOSS
twitter - @nfonrose / @teevity

**Comment by klausfiend** [comment]
Hi Nicolas,

What's the normal way to set up a dummy billing file? My thought is: create a new bucket, scrape some lines from an existing file into a new one and drop it in the new bucket with a name that matches the default naming scheme, and point the application at that bucket instead?

How do I disable RI polling (I wouldn't mind doing this anyway, it generates a ton of noise in the logs)? Is it that controlled by _ice.reservationCapacityPoller=false_ or is there another setting I'm overlooking?
