### ISSUE TITLE
ERROR basic.BasicReservationService - No Zone for ap-south-1c [doesn't actually exist]

### ISSUE THREAD

**Issue by alphacentauri82** [Teevity/ice#290]
Running the dockerised version. I noticed that adding or removing the ap-south-1c from Zones doesn't do the trick.. it starts scraping information for RI prices for ap-south-1 and spits: (bah.. it just had to be deleted)

```ice_1    | 2019-06-11 13:44:34,013 [localhost-startStop-1] INFO  basic.BasicReservationService  - Setting RI price for ap-south-1 HEAVY c4.large.windows 0.0 0.147
ice_1    | 2019-06-11 13:44:34,013 [localhost-startStop-1] INFO  basic.BasicReservationService  - Setting RI price for ap-south-1 HEAVY d2.4xlarge.windows 206345.0 0.0
ice_1    | | Error 2019-06-11 13:44:34,014 [localhost-startStop-1] ERROR basic.BasicReservationService  - No Zone for ap-south-1c
ice_1    | 2019-06-11 13:44:34,014 [localhost-startStop-1] INFO  basic.BasicReservationService  - Setting RI price for ap-south-1 HEAVY m5.2xlarge.rhel 0.0 0.307
ice_1    | | Error 2019-06-11 13:44:34,014 [localhost-startStop-1] ERROR basic.BasicReservationService  - No Zone for ap-south-1c
ice_1    | | Error 2019-06-11 13:44:34,015 [localhost-startStop-1] ERROR basic.BasicReservationService  - No Zone for ap-south-1c```

**Comment by revbingo** [comment]
I'm facing this issue too, but it's not clear what you deleted to resolve it?

**Comment by nfonrose** [comment]
Hi Mark,

Is this error preventing your Ice instance from starting?

If not, not having these files is only an issue if you want to see the
"upfront cost of RIs amortized over their usage period".
If you only care about the "hourly paid costs of EC2 instances", not having
this data is not an issue.

Nicolas

PS : These files that Ice is trying to load are EC2 price files which are
also generated by Ice, in a way that was the only one possible before the
"AWS ListPrice API".
It's now an outdated way of gathering EC2 price data. Jim Roth's Ice fork
<https://github.com/jimroth/ice> is up-to-date on this topic and no longer
use these files.

--
Nicolas Fonrose | Teevity | Founder
+33.6.61.35.43.31
https://teevity.com - Cloud Costs Analytics for AWS, GCP and Azure powered
by NetflixOSS Ice
twitter - @nfonrose / @teevity

**Comment by revbingo** [comment]
Hi Nicolas - it was spinning for quite a while so I thought it was not going to start, but eventually it does, so not a blocker, thanks.
